[package]
name = "nineteen"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.8.0"
rayon = "1.6.1"
scan_fmt = "0.2.6"
