[package]
name = "five"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
test_utils = { path = "../test_utils" }
scan_fmt = "0.2.6"

[dev-dependencies]
anyhow = "1"

